<template>
    <div class="Form">
        <h2>b-checkbox</h2>
        <hr>
        <div class="row">
            <font class="col-1">default:</font>
            <b-checkbox-tree :list="list" v-model="values"></b-checkbox-tree>
        </div>
        <div class="row">
            <font class="col-1">disabled:</font>
            <b-checkbox-tree :list="list" disabled></b-checkbox-tree>
        </div>
        {{ values }}
    </div>
</template>

<script>
import BCheckboxTree from '@/components/base/Bootstrap/Form/CheckBox/CheckBoxTree/b-checkbox-tree.vue'

export default {
    name: 'b-checkbox-tree-demo',
    components: { BCheckboxTree },
    data () {
        return {
            values: [ { "value": "2-a", "label": "2-a" }, { "value": "3-a", "label": "3-a" }, { "value": "4-1-b", "label": "4-1-b" }, { value: '3-1-a', label: '3-1-a' } ],
            list: [
                { label: '1-a', value: '1-a', 
                children: [
                    { label: '2-a', value: '2-a', },
                    { label: '2-b', value: '2-b', },
                    { label: '2-c', value: '2-c', },
                    { label: '2-d', value: '2-d', },
                ],},
                { label: '1-b', value: '1-b', 
                children: [
                    { label: '3-a', value: '3-a', },
                    { label: '3-b', value: '3-b', 
                    children: [
                        { label: '3-1-0a', value: '3-1-0a', },
                        { label: '3-1-0b', value: '3-1-0b', },
                        { label: '3-1-0c', value: '3-1-0c', },
                        { label: '3-1-0d', value: '3-1-0d', },
                        { label: '3-1-0f', value: '3-1-0f', },
                        { label: '3-1-0g', value: '3-1-0g', },
                        { label: '3-1-0h', value: '3-1-0h', },
                        { label: '3-1-0i', value: '3-1-0i', },
                        { label: '3-1-0j', value: '3-1-0j', },
                        { label: '3-1-0k', value: '3-1-0k', },
                        { label: '3-1-0l', value: '3-1-0l', },
                        { label: '3-1-0m', value: '3-1-0m', },
                        { label: '3-1-0n', value: '3-1-0n', },
                        { label: '3-1-0o', value: '3-1-0o', },
                        { label: '3-1-0p', value: '3-1-0p', },
                        { label: '3-1-0q', value: '3-1-0q', },
                        { label: '3-1-0r', value: '3-1-0r', },
                        { label: '3-1-0s', value: '3-1-0s', },
                        { label: '3-1-0t', value: '3-1-0t', },
                        { label: '3-1-0u', value: '3-1-0u', },
                        { label: '3-1-0v', value: '3-1-0v', },
                        { label: '3-1-0w', value: '3-1-0w', },
                        { label: '3-1-0x', value: '3-1-0x', },
                        { label: '3-1-0y', value: '3-1-0y', },
                        { label: '3-1-0z', value: '3-1-0z', },

                        { label: '3-1-1a', value: '3-1-1a', },
                        { label: '3-1-1b', value: '3-1-1b', },
                        { label: '3-1-1c', value: '3-1-1c', },
                        { label: '3-1-1d', value: '3-1-1d', },
                        { label: '3-1-1f', value: '3-1-1f', },
                        { label: '3-1-1g', value: '3-1-1g', },
                        { label: '3-1-1h', value: '3-1-1h', },
                        { label: '3-1-1i', value: '3-1-1i', },
                        { label: '3-1-1j', value: '3-1-1j', },
                        { label: '3-1-1k', value: '3-1-1k', },
                        { label: '3-1-1l', value: '3-1-1l', },
                        { label: '3-1-1m', value: '3-1-1m', },
                        { label: '3-1-1n', value: '3-1-1n', },
                        { label: '3-1-1o', value: '3-1-1o', },
                        { label: '3-1-1p', value: '3-1-1p', },
                        { label: '3-1-1q', value: '3-1-1q', },
                        { label: '3-1-1r', value: '3-1-1r', },
                        { label: '3-1-1s', value: '3-1-1s', },
                        { label: '3-1-1t', value: '3-1-1t', },
                        { label: '3-1-1u', value: '3-1-1u', },
                        { label: '3-1-1v', value: '3-1-1v', },
                        { label: '3-1-1w', value: '3-1-1w', },
                        { label: '3-1-1x', value: '3-1-1x', },
                        { label: '3-1-1y', value: '3-1-1y', },
                        { label: '3-1-1z', value: '3-1-1z', },

                        { label: '3-1-2a', value: '3-1-2a', },
                        { label: '3-1-2b', value: '3-1-2b', },
                        { label: '3-1-2c', value: '3-1-2c', },
                        { label: '3-1-2d', value: '3-1-2d', },
                        { label: '3-1-2f', value: '3-1-2f', },
                        { label: '3-1-2g', value: '3-1-2g', },
                        { label: '3-1-2h', value: '3-1-2h', },
                        { label: '3-1-2i', value: '3-1-2i', },
                        { label: '3-1-2j', value: '3-1-2j', },
                        { label: '3-1-2k', value: '3-1-2k', },
                        { label: '3-1-2l', value: '3-1-2l', },
                        { label: '3-1-2m', value: '3-1-2m', },
                        { label: '3-1-2n', value: '3-1-2n', },
                        { label: '3-1-2o', value: '3-1-2o', },
                        { label: '3-1-2p', value: '3-1-2p', },
                        { label: '3-1-2q', value: '3-1-2q', },
                        { label: '3-1-2r', value: '3-1-2r', },
                        { label: '3-1-2s', value: '3-1-2s', },
                        { label: '3-1-2t', value: '3-1-2t', },
                        { label: '3-1-2u', value: '3-1-2u', },
                        { label: '3-1-2v', value: '3-1-2v', },
                        { label: '3-1-2w', value: '3-1-2w', },
                        { label: '3-1-2x', value: '3-1-2x', },
                        { label: '3-1-2y', value: '3-1-2y', },
                        { label: '3-1-2z', value: '3-1-2z', },
                        
                        { label: '3-1-3a', value: '3-1-3a', },
                        { label: '3-1-3b', value: '3-1-3b', },
                        { label: '3-1-3c', value: '3-1-3c', },
                        { label: '3-1-3d', value: '3-1-3d', },
                        { label: '3-1-3f', value: '3-1-3f', },
                        { label: '3-1-3g', value: '3-1-3g', },
                        { label: '3-1-3h', value: '3-1-3h', },
                        { label: '3-1-3i', value: '3-1-3i', },
                        { label: '3-1-3j', value: '3-1-3j', },
                        { label: '3-1-3k', value: '3-1-3k', },
                        { label: '3-1-3l', value: '3-1-3l', },
                        { label: '3-1-3m', value: '3-1-3m', },
                        { label: '3-1-3n', value: '3-1-3n', },
                        { label: '3-1-3o', value: '3-1-3o', },
                        { label: '3-1-3p', value: '3-1-3p', },
                        { label: '3-1-3q', value: '3-1-3q', },
                        { label: '3-1-3r', value: '3-1-3r', },
                        { label: '3-1-3s', value: '3-1-3s', },
                        { label: '3-1-3t', value: '3-1-3t', },
                        { label: '3-1-3u', value: '3-1-3u', },
                        { label: '3-1-3v', value: '3-1-3v', },
                        { label: '3-1-3w', value: '3-1-3w', },
                        { label: '3-1-3x', value: '3-1-3x', },
                        { label: '3-1-3y', value: '3-1-3y', },
                        { label: '3-1-3z', value: '3-1-3z', },

                        { label: '3-1-4a', value: '3-1-4a', },
                        { label: '3-1-4b', value: '3-1-4b', },
                        { label: '3-1-4c', value: '3-1-4c', },
                        { label: '3-1-4d', value: '3-1-4d', },
                        { label: '3-1-4f', value: '3-1-4f', },
                        { label: '3-1-4g', value: '3-1-4g', },
                        { label: '3-1-4h', value: '3-1-4h', },
                        { label: '3-1-4i', value: '3-1-4i', },
                        { label: '3-1-4j', value: '3-1-4j', },
                        { label: '3-1-4k', value: '3-1-4k', },
                        { label: '3-1-4l', value: '3-1-4l', },
                        { label: '3-1-4m', value: '3-1-4m', },
                        { label: '3-1-4n', value: '3-1-4n', },
                        { label: '3-1-4o', value: '3-1-4o', },
                        { label: '3-1-4p', value: '3-1-4p', },
                        { label: '3-1-4q', value: '3-1-4q', },
                        { label: '3-1-4r', value: '3-1-4r', },
                        { label: '3-1-4s', value: '3-1-4s', },
                        { label: '3-1-4t', value: '3-1-4t', },
                        { label: '3-1-4u', value: '3-1-4u', },
                        { label: '3-1-4v', value: '3-1-4v', },
                        { label: '3-1-4w', value: '3-1-4w', },
                        { label: '3-1-4x', value: '3-1-4x', },
                        { label: '3-1-4y', value: '3-1-4y', },
                        { label: '3-1-4z', value: '3-1-4z', },

                        { label: '3-1-5a', value: '3-1-5a', },
                        { label: '3-1-5b', value: '3-1-5b', },
                        { label: '3-1-5c', value: '3-1-5c', },
                        { label: '3-1-5d', value: '3-1-5d', },
                        { label: '3-1-5f', value: '3-1-5f', },
                        { label: '3-1-5g', value: '3-1-5g', },
                        { label: '3-1-5h', value: '3-1-5h', },
                        { label: '3-1-5i', value: '3-1-5i', },
                        { label: '3-1-5j', value: '3-1-5j', },
                        { label: '3-1-5k', value: '3-1-5k', },
                        { label: '3-1-5l', value: '3-1-5l', },
                        { label: '3-1-5m', value: '3-1-5m', },
                        { label: '3-1-5n', value: '3-1-5n', },
                        { label: '3-1-5o', value: '3-1-5o', },
                        { label: '3-1-5p', value: '3-1-5p', },
                        { label: '3-1-5q', value: '3-1-5q', },
                        { label: '3-1-5r', value: '3-1-5r', },
                        { label: '3-1-5s', value: '3-1-5s', },
                        { label: '3-1-5t', value: '3-1-5t', },
                        { label: '3-1-5u', value: '3-1-5u', },
                        { label: '3-1-5v', value: '3-1-5v', },
                        { label: '3-1-5w', value: '3-1-5w', },
                        { label: '3-1-5x', value: '3-1-5x', },
                        { label: '3-1-5y', value: '3-1-5y', },
                        { label: '3-1-5z', value: '3-1-5z', },

                        { label: '3-1-6a', value: '3-1-6a', },
                        { label: '3-1-6b', value: '3-1-6b', },
                        { label: '3-1-6c', value: '3-1-6c', },
                        { label: '3-1-6d', value: '3-1-6d', },
                        { label: '3-1-6f', value: '3-1-6f', },
                        { label: '3-1-6g', value: '3-1-6g', },
                        { label: '3-1-6h', value: '3-1-6h', },
                        { label: '3-1-6i', value: '3-1-6i', },
                        { label: '3-1-6j', value: '3-1-6j', },
                        { label: '3-1-6k', value: '3-1-6k', },
                        { label: '3-1-6l', value: '3-1-6l', },
                        { label: '3-1-6m', value: '3-1-6m', },
                        { label: '3-1-6n', value: '3-1-6n', },
                        { label: '3-1-6o', value: '3-1-6o', },
                        { label: '3-1-6p', value: '3-1-6p', },
                        { label: '3-1-6q', value: '3-1-6q', },
                        { label: '3-1-6r', value: '3-1-6r', },
                        { label: '3-1-6s', value: '3-1-6s', },
                        { label: '3-1-6t', value: '3-1-6t', },
                        { label: '3-1-6u', value: '3-1-6u', },
                        { label: '3-1-6v', value: '3-1-6v', },
                        { label: '3-1-6w', value: '3-1-6w', },
                        { label: '3-1-6x', value: '3-1-6x', },
                        { label: '3-1-6y', value: '3-1-6y', },
                        { label: '3-1-6z', value: '3-1-6z', },

                        { label: '3-1-7a', value: '3-1-7a', },
                        { label: '3-1-7b', value: '3-1-7b', },
                        { label: '3-1-7c', value: '3-1-7c', },
                        { label: '3-1-7d', value: '3-1-7d', },
                        { label: '3-1-7f', value: '3-1-7f', },
                        { label: '3-1-7g', value: '3-1-7g', },
                        { label: '3-1-7h', value: '3-1-7h', },
                        { label: '3-1-7i', value: '3-1-7i', },
                        { label: '3-1-7j', value: '3-1-7j', },
                        { label: '3-1-7k', value: '3-1-7k', },
                        { label: '3-1-7l', value: '3-1-7l', },
                        { label: '3-1-7m', value: '3-1-7m', },
                        { label: '3-1-7n', value: '3-1-7n', },
                        { label: '3-1-7o', value: '3-1-7o', },
                        { label: '3-1-7p', value: '3-1-7p', },
                        { label: '3-1-7q', value: '3-1-7q', },
                        { label: '3-1-7r', value: '3-1-7r', },
                        { label: '3-1-7s', value: '3-1-7s', },
                        { label: '3-1-7t', value: '3-1-7t', },
                        { label: '3-1-7u', value: '3-1-7u', },
                        { label: '3-1-7v', value: '3-1-7v', },
                        { label: '3-1-7w', value: '3-1-7w', },
                        { label: '3-1-7x', value: '3-1-7x', },
                        { label: '3-1-7y', value: '3-1-7y', },
                        { label: '3-1-7z', value: '3-1-7z', },

                        { label: '3-1-8a', value: '3-1-8a', },
                        { label: '3-1-8b', value: '3-1-8b', },
                        { label: '3-1-8c', value: '3-1-8c', },
                        { label: '3-1-8d', value: '3-1-8d', },
                        { label: '3-1-8f', value: '3-1-8f', },
                        { label: '3-1-8g', value: '3-1-8g', },
                        { label: '3-1-8h', value: '3-1-8h', },
                        { label: '3-1-8i', value: '3-1-8i', },
                        { label: '3-1-8j', value: '3-1-8j', },
                        { label: '3-1-8k', value: '3-1-8k', },
                        { label: '3-1-8l', value: '3-1-8l', },
                        { label: '3-1-8m', value: '3-1-8m', },
                        { label: '3-1-8n', value: '3-1-8n', },
                        { label: '3-1-8o', value: '3-1-8o', },
                        { label: '3-1-8p', value: '3-1-8p', },
                        { label: '3-1-8q', value: '3-1-8q', },
                        { label: '3-1-8r', value: '3-1-8r', },
                        { label: '3-1-8s', value: '3-1-8s', },
                        { label: '3-1-8t', value: '3-1-8t', },
                        { label: '3-1-8u', value: '3-1-8u', },
                        { label: '3-1-8v', value: '3-1-8v', },
                        { label: '3-1-8w', value: '3-1-8w', },
                        { label: '3-1-8x', value: '3-1-8x', },
                        { label: '3-1-8y', value: '3-1-8y', },
                        { label: '3-1-8z', value: '3-1-8z', },

                        { label: '3-1-9a', value: '3-1-9a', },
                        { label: '3-1-9b', value: '3-1-9b', },
                        { label: '3-1-9c', value: '3-1-9c', },
                        { label: '3-1-9d', value: '3-1-9d', },
                        { label: '3-1-9f', value: '3-1-9f', },
                        { label: '3-1-9g', value: '3-1-9g', },
                        { label: '3-1-9h', value: '3-1-9h', },
                        { label: '3-1-9i', value: '3-1-9i', },
                        { label: '3-1-9j', value: '3-1-9j', },
                        { label: '3-1-9k', value: '3-1-9k', },
                        { label: '3-1-9l', value: '3-1-9l', },
                        { label: '3-1-9m', value: '3-1-9m', },
                        { label: '3-1-9n', value: '3-1-9n', },
                        { label: '3-1-9o', value: '3-1-9o', },
                        { label: '3-1-9p', value: '3-1-9p', },
                        { label: '3-1-9q', value: '3-1-9q', },
                        { label: '3-1-9r', value: '3-1-9r', },
                        { label: '3-1-9s', value: '3-1-9s', },
                        { label: '3-1-9t', value: '3-1-9t', },
                        { label: '3-1-9u', value: '3-1-9u', },
                        { label: '3-1-9v', value: '3-1-9v', },
                        { label: '3-1-9w', value: '3-1-9w', },
                        { label: '3-1-9x', value: '3-1-9x', },
                        { label: '3-1-9y', value: '3-1-9y', },
                        { label: '3-1-9z', value: '3-1-9z', },
                    ]},
                    { label: '4-b', value: '4-b', 
                    children: [
                        { label: '4-1-a', value: '4-1-a', },
                        { label: '4-1-b', value: '4-1-b', },
                        { label: '4-1-c', value: '4-1-c', },
                        { label: '4-1-d', value: '4-1-d', },
                    ]},
                ]},
            ],
            list2: [
                { label: '1-a', value: '1-a', 
                children: [
                    { label: '2-a', value: '2-a', },
                    { label: '2-b', value: '2-b', },
                    { label: '2-c', value: '2-c', },
                    { label: '2-d', value: '2-d', },
                ],},
                { label: '1-b', value: '1-b', 
                children: [
                    { label: '3-a', value: '3-a', },
                    { label: '3-b', value: '3-b', 
                    children: [
                    { label: '3-1-a', value: '3-1-a', },
                    { label: '3-1-b', value: '3-1-b', },
                    { label: '3-1-c', value: '3-1-c', },
                    { label: '3-1-d', value: '3-1-d', },
                ]},
                    { label: '3-c', value: '3-c', },
                    { label: '3-d', value: '3-d', },
                ]},
                { label: '1-c', value: '1-c', },
                { label: '1-d', value: '1-d', children: [
                    { label: '4-a', value: '4-a', },
                    { label: '4-b', value: '4-b', },
                    { label: '4-c', value: '4-c', },
                    { label: '4-d', value: '4-d', },
                ]},
            ],
        }
    }
}
</script>
